



export const REGISTER_USERCOMPANY = "REGISTER_USERCOMPANY";

export const LOGIN_USERCOMPANY= "LOGIN_USERCOMPANY";

export const LOGOUT_USERCOMPANY="LOGOUT_USERCOMPANY";

export const LOAD_USERCOMPANY="LOAD_USERCOMPANY";

export const FAIL_USERCOMPANY="FAIL_USERCOMPANY";



export const GET_COMPANY_LOAD ="GET_COMPANY_LOAD";
export const GET_COMPANY_SUCCESS="GET_COMPANY_SUCCESS";
export const GET_COMPANY_FAIL="GET_COMPANY_FAIL";

export const CURRENT_USERCOMPANY="CURRENT_USERCOMPANY";


export const GET_COMPANY_LOAD_BY_ID="GET_COMPANY_LOAD_BY_ID";
export const GET_COMPANY_SUCCESS_BY_ID="GET_COMPANY_SUCCESS_BY_ID";
export const GET_COMPANY_FAIL_BY_ID="GET_COMPANY _FAIL_BY_ID";



