

export const REGISTER_USERMODEL = "REGISTER_USERMODEL";

export const LOGIN_USERMODEL= "LOGIN_USERMODEL";

export const LOGOUT_USERMODEL="LOGOUT_USERMODEL";

export const LOAD_USERMODEL="LOAD_USERMODEL";

export const FAIL_USERMODEL="FAIL_USERMODEL";

export const CURRENT_USERMODEL="CURRENT_USERMODEL";

export const GET_MODELS_LOAD ="GET_MODELS_LOAD";
export const GET_MODELS_SUCCESS="GET_MODELS_SUCCESS";
export const GET_MODELS_FAIL="GET_MODELS_FAIL";



export const GET_MODELS_LOAD_BY_ID="GET_MODELS_LOAD_BY_ID";
export const GET_MODELS_SUCCESS_BY_ID="GET_MODELS_SUCCESS_BY_ID";
export const GET_MODELS_FAIL_BY_ID="GET_MODELS_FAIL_BY_ID";



